# this script trains a simple character-level spelling corrector using TensorFlow
# it reads the data generated by generate_spelling_data.py, encodes the words as numbers
from pathlib import Path
import sys

import numpy as np
import tensorflow as tf

np.random.seed(1)
tf.random.set_seed(1)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = PROJECT_ROOT / "data" / "spelling_pairs.csv"

sys.path.append(str(PROJECT_ROOT))

from dtsc330_26.readers.spelling_reader import read_spelling_pairs


def make_character_lookup(words):
    """
    create mappings:
    char -> number
    number -> char
    """

    # get all unique characters from all words
    characters = sorted(list(set("".join(words)))) + [" "]

    # map each char to a number
    char_to_num = {char: i + 1 for i, char in enumerate(characters)}

    # reverse mapping
    num_to_char = {i + 1: char for i, char in enumerate(characters)}

    return char_to_num, num_to_char


def encode_words(words, char_to_num, max_length):
    """
    turn words into numbers + pad them so same length
    """

    encoded_words = []

    for word in words:
        # convert each char to its number
        encoded = [char_to_num[char] for char in word]

        # pad shorter words with spaces
        while len(encoded) < max_length:
            encoded.append(char_to_num[" "])

        # make sure nothing goes over max_length
        encoded_words.append(encoded[:max_length])

    return np.array(encoded_words)


def decode_word(encoded_word, num_to_char):
    """
    turn numbers back into a word (for printing results)
    """

    letters = []

    for number in encoded_word:
        if number in num_to_char:
            letters.append(num_to_char[number])

    return "".join(letters).strip()


def build_model(vocab_size):
    """
    build a simple model:
    embedding -> lstm -> predict characters
    """

    model = tf.keras.Sequential([
        # turns numbers into vectors
        tf.keras.layers.Embedding(vocab_size + 1, 16),

        # learns patterns in sequences
        tf.keras.layers.LSTM(128, return_sequences=True),

        # for each position, predict the correct character
        tf.keras.layers.Dense(vocab_size + 1, activation="softmax"),
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    return model


def main():
    """
    whole pipeline:
    load data -> encode -> train -> predict
    """

    # load csv
    spelling_data = read_spelling_pairs(DATA_PATH)

    # inputs (wrong words)
    misspelled_words = spelling_data["misspelled"].astype(str).tolist()

    # outputs (correct words)
    correct_words = spelling_data["correct"].astype(str).tolist()

    # combine everything to build vocab
    all_words = misspelled_words + correct_words

    # find longest word
    max_length = max(len(word) for word in all_words)

    # create char <-> number mappings
    char_to_num, num_to_char = make_character_lookup(all_words)

    # encode inputs
    x = encode_words(misspelled_words, char_to_num, max_length)

    # encode outputs
    y = encode_words(correct_words, char_to_num, max_length)

    # tf needs this extra dimension
    y = np.expand_dims(y, -1)

    # build model
    model = build_model(len(char_to_num))

    # train model
    model.fit(x, y, epochs=200, verbose=1)

    # get predictions
    predictions = model.predict(x)

    print("\nexample predictions:")

    for i in range(10):
        # pick most likely character at each position
        predicted_numbers = np.argmax(predictions[i], axis=1)

        # turn back into word
        predicted_word = decode_word(predicted_numbers, num_to_char)

        print(f"{misspelled_words[i]} -> {predicted_word} | correct: {correct_words[i]}")


if __name__ == "__main__":
    main()
